//
//  EconomyNewsService.swift
//  Billix
//
//  Created by Claude Code on 1/24/26.
//  Service for fetching economy news articles from Supabase
//

import Foundation
import Supabase

/// Service for fetching economy news articles
/// Articles are generated by the fetch-economy-news Edge Function and cached in Supabase
@MainActor
class EconomyNewsService {
    static let shared = EconomyNewsService()

    private let supabase = SupabaseService.shared.client

    private init() {}

    // MARK: - Fetch Articles

    /// Fetch all economy articles, sorted by published date
    func fetchArticles(limit: Int = 50) async throws -> [EconomyArticle] {
        let response: [EconomyArticleDB] = try await supabase
            .from("economy_articles")
            .select()
            .order("published_at", ascending: false)
            .limit(limit)
            .execute()
            .value

        return response.map { EconomyArticle(from: $0) }
    }

    /// Fetch featured news articles only
    func fetchFeaturedNews(limit: Int = 5) async throws -> [EconomyArticle] {
        let response: [EconomyArticleDB] = try await supabase
            .from("economy_articles")
            .select()
            .eq("is_breaking", value: true)
            .order("published_at", ascending: false)
            .limit(limit)
            .execute()
            .value

        return response.map { EconomyArticle(from: $0) }
    }

    /// Fetch articles by category
    func fetchArticles(category: EconomyCategory, limit: Int = 20) async throws -> [EconomyArticle] {
        guard category != .all else {
            return try await fetchArticles(limit: limit)
        }

        let response: [EconomyArticleDB] = try await supabase
            .from("economy_articles")
            .select()
            .eq("category", value: category.dbValue)
            .order("published_at", ascending: false)
            .limit(limit)
            .execute()
            .value

        return response.map { EconomyArticle(from: $0) }
    }

    // MARK: - Trigger Refresh

    /// Trigger the Edge Function to fetch new articles from NewsData.io
    /// This should be called sparingly (once per day) to conserve API credits
    func triggerNewsRefresh() async throws -> NewsRefreshResult {
        let result: NewsRefreshResult = try await supabase.functions.invoke(
            "fetch-economy-news",
            options: FunctionInvokeOptions(method: .post),
            decode: { data, _ in
                let decoder = JSONDecoder()
                return try decoder.decode(NewsRefreshResult.self, from: data)
            }
        )
        return result
    }
}

// MARK: - Response Types

struct NewsRefreshResult: Codable {
    let success: Bool
    let articlesProcessed: Int?
    let articlesSkipped: Int?
    let totalReceived: Int?
    let error: String?
    let message: String?
}
